# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_player_elo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1200)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Competition')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='elo',
        ),
        migrations.AddField(
            model_name='elos',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='boards.Player'),
        ),
    ]
