# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20170402_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elos',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Player'),
        ),
    ]
