# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20170402_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elos',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='elos',
            name='player',
        ),
        migrations.DeleteModel(
            name='Elos',
        ),
    ]
